import type { BlogPost } from "./types"

export const defaultBlogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "sustainable-luxury-living",
    title: "The Future of Sustainable Luxury Living in Munich",
    excerpt: "Discover how modern building techniques and sustainable materials are reshaping the luxury real estate landscape in Munich, creating homes that are as kind to the environment as they are beautiful to live in.",
    category: "Sustainability",
    author: "Gagan Bau Team",
    date: "January 15, 2026",
    readTime: "6 min read",
    image: "/images/blog-hero.jpg",
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    id: "2",
    slug: "munich-real-estate-trends-2026",
    title: "Munich Real Estate Market Trends for 2026",
    excerpt: "An in-depth analysis of the Munich property market, key neighborhoods to watch, and investment opportunities in the coming year.",
    category: "Market Insights",
    author: "Gagan Bau Team",
    date: "January 8, 2026",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop&auto=format",
    featured: false,
    order: 2,
    isActive: true,
  },
  {
    id: "3",
    slug: "interior-design-trends",
    title: "Interior Design Trends Shaping Premium Residences",
    excerpt: "From biophilic design to smart home integration, explore the interior trends that define contemporary luxury living spaces.",
    category: "Design",
    author: "Gagan Bau Team",
    date: "December 20, 2025",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=500&fit=crop&auto=format",
    featured: false,
    order: 3,
    isActive: true,
  },
  {
    id: "4",
    slug: "community-building-in-residential",
    title: "Building Communities, Not Just Residences",
    excerpt: "How thoughtful urban planning and shared amenities create vibrant communities within residential developments.",
    category: "Community",
    author: "Gagan Bau Team",
    date: "December 12, 2025",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop&auto=format",
    featured: false,
    order: 4,
    isActive: true,
  },
  {
    id: "5",
    slug: "energy-efficient-construction",
    title: "Energy Efficiency in Modern Construction: A Deep Dive",
    excerpt: "Exploring the latest technologies and methodologies that make new buildings dramatically more energy-efficient without compromising comfort.",
    category: "Sustainability",
    author: "Gagan Bau Team",
    date: "November 28, 2025",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=500&fit=crop&auto=format",
    featured: false,
    order: 5,
    isActive: true,
  },
  {
    id: "6",
    slug: "choosing-right-neighborhood",
    title: "How to Choose the Right Neighborhood in Munich",
    excerpt: "A comprehensive guide to Munich's most desirable neighborhoods, from family-friendly suburbs to vibrant urban districts.",
    category: "Guide",
    author: "Gagan Bau Team",
    date: "November 15, 2025",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=500&fit=crop&auto=format",
    featured: false,
    order: 6,
    isActive: true,
  },
]
